### ISSUE TITLE
Changing the size of space-objekt creates an errro

### ISSUE THREAD

**Issue by BrianBrandner** [ChrisThor/SpaceGame#4]
When creating new space-objekt and changing the size below zero this error pops up.

`Traceback (most recent call last):
  File "main.py", line 474, in <module>
    main()                         
  File "main.py", line 290, in main
    screen_height, screen_width, small_stars, space, static_stars, template_space_object, zoom_factor)
  File "main.py", line 317, in draw_frame
    screen_height, screen_width, space, zoom_factor, template_space_object)
  File "main.py", line 386, in draw_space_objects
    int(2 * zoom_factor))
ValueError: negative radius
`

**Comment by ChrisThor** [comment]
Aghhhh I see. Lemme fix it real quick!
